### ISSUE TITLE
Gradle build fails, but works in IntelliJ

### ISSUE THREAD

**Issue by Chris-Johnston** [UWB-ACM/DiscordBot_Java#1]
I'm using Linux Mint 18, if it's a configuration issue. Unfortunately I don't know a lot about gradle, so I'm not sure how useful I can be for debugging this.

Running `gradle build` or `gradle run` in the project root produces this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.reflect.UndeclaredThrowableException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed
```

Running `gradle idea` and opening the project in IntelliJ works just fine though.

**Comment by bpas247** [comment]
What version of Java are you running? Also, are you able to run any of the other Gradle commands in the project root?

**Comment by Chris-Johnston** [comment]
`gradle idea` worked just fine.

```
$ gradle --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          9-internal (Oracle Corporation 9-internal+0-2016-04-14-195246.buildd.src)
OS:           Linux 4.10.0-38-generic amd64
```

```
$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by bpas247** [comment]
I added a commit that referenced this issue, although I am not sure if it actually fixes the issue. @Chris-Johnston can you confirm if you are still having this issue or not?

**Comment by Chris-Johnston** [comment]
Oh, figured out the issue. Turns out that it was a system problem and not a code problem.

Solution was to install java 8 with `sdk install java`.

https://github.com/gradle/gradle/issues/2481

Now it works as expected.
